// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/materiales" | "/admin/materiales/nuevo" | "/inmuebles" | "/inmuebles/[id]" | "/inmuebles/nuevo" | "/items" | "/items/[id]/calcular" | "/items/[id]/materiales" | "/items/editar/[id]" | "/items/nuevo" | "/login" | "/materiales" | "/materiales/editar/[id]" | "/materiales/nuevo" | "/proveedor/materiales" | "/proveedor/materiales/nuevo" | "/proyectos" | "/proyectos/[id]" | "/proyectos/[id]/obra" | "/proyectos/[id]/obra/configurar" | "/proyectos/editar/[id]" | "/proyectos/nuevo" | "/referencia" | "/referencia/[id]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin/materiales": {}
  "/admin/materiales/nuevo": {}
  "/inmuebles": {}
  "/inmuebles/[id]": { "id": string; }
  "/inmuebles/nuevo": {}
  "/items": {}
  "/items/[id]/calcular": { "id": string; }
  "/items/[id]/materiales": { "id": string; }
  "/items/editar/[id]": { "id": string; }
  "/items/nuevo": {}
  "/login": {}
  "/materiales": {}
  "/materiales/editar/[id]": { "id": string; }
  "/materiales/nuevo": {}
  "/proveedor/materiales": {}
  "/proveedor/materiales/nuevo": {}
  "/proyectos": {}
  "/proyectos/[id]": { "id": string; }
  "/proyectos/[id]/obra": { "id": string; }
  "/proyectos/[id]/obra/configurar": { "id": string; }
  "/proyectos/editar/[id]": { "id": string; }
  "/proyectos/nuevo": {}
  "/referencia": {}
  "/referencia/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
