// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/admin/materiales/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/materiales/nuevo">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/materiales/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/materiales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/materiales">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/materiales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inmuebles/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inmuebles/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/inmuebles/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inmuebles/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inmuebles/nuevo">> = Specific
  const handler = {} as typeof import("../../../src/app/inmuebles/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inmuebles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inmuebles">> = Specific
  const handler = {} as typeof import("../../../src/app/inmuebles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/items/[id]/calcular/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/items/[id]/calcular">> = Specific
  const handler = {} as typeof import("../../../src/app/items/[id]/calcular/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/items/[id]/materiales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/items/[id]/materiales">> = Specific
  const handler = {} as typeof import("../../../src/app/items/[id]/materiales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/items/editar/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/items/editar/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/items/editar/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/items/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/items/nuevo">> = Specific
  const handler = {} as typeof import("../../../src/app/items/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/items">> = Specific
  const handler = {} as typeof import("../../../src/app/items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/materiales/editar/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materiales/editar/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/materiales/editar/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/materiales/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materiales/nuevo">> = Specific
  const handler = {} as typeof import("../../../src/app/materiales/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/materiales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materiales">> = Specific
  const handler = {} as typeof import("../../../src/app/materiales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/proveedor/materiales/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proveedor/materiales/nuevo">> = Specific
  const handler = {} as typeof import("../../../src/app/proveedor/materiales/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/proveedor/materiales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proveedor/materiales">> = Specific
  const handler = {} as typeof import("../../../src/app/proveedor/materiales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/proyectos/[id]/obra/configurar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proyectos/[id]/obra/configurar">> = Specific
  const handler = {} as typeof import("../../../src/app/proyectos/[id]/obra/configurar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/proyectos/[id]/obra/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proyectos/[id]/obra">> = Specific
  const handler = {} as typeof import("../../../src/app/proyectos/[id]/obra/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/proyectos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proyectos/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/proyectos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/proyectos/editar/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proyectos/editar/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/proyectos/editar/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/proyectos/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proyectos/nuevo">> = Specific
  const handler = {} as typeof import("../../../src/app/proyectos/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/proyectos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proyectos">> = Specific
  const handler = {} as typeof import("../../../src/app/proyectos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/referencia/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referencia/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/referencia/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/referencia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referencia">> = Specific
  const handler = {} as typeof import("../../../src/app/referencia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
